<?php
include("fonctions.php");
mysqli_set_charset(bddConnect(), "utf8");

$CODEANIM = $_GET['CODEANIM'];
$CDTYPEANIM = $_POST['CODETYPEANIM'];
$NOMANIM = $_POST['NOMANIM'];
$DATEVALIDITEANIM = $_POST['DATEVALIDITEANIM'];
$DUREEANIM = $_POST['DUREEANIM'];
$LIMITEAGE = $_POST['LIMITEAGE'];
$TARIFANIM = $_POST['TARIFANIM'];
$NBREPLACEANIM = $_POST['NBREPLACEANIM'];
$DESCRIPTANIM = $_POST['DESCRIPTANIM'];
$COMMENTANIM = $_POST['COMMENTANIM'];
$DIFFICULTANIM = $_POST['DIFFICULTEANIM'];

#Requete pour mettre à jour l'animation choisi
$requete = "UPDATE ANIMATION SET CODETYPEANIM=$CDTYPEANIM, NOMANIM = $NOMANIM, NOW(),
DATEVALIDITEANIM = $DATEVALIDITEANIM, DUREEANIM = $DUREEANIM, LIMITEAGE = $LIMITEAGE,
TARIFANIM = $TARIFANIM, NBREPLACEANIM = $NBREPLACEANIM, DESCRIPTANIM = $DESCRIPTANIM,
COMMENTANIM = $COMMENTANIM, DIFFICULTEANIM = $DIFFICULTANIM WHERE CODEANIM = $CODEANIM";
$resultat = mysqli_query(bddConnect(), $requete);
echo "L'animation a bien été modifié";
header('Refresh: 10; url=index.php?index=animation');










 ?>
