#Créer une animation
<?php
include("fonctions.php");
mysqli_set_charset(bddConnect(), "utf8");
$CDANIM = $_POST['CODEANIM'];
$CDTYPEANIM = $_POST['CODETYPEANIM'];
$NOMANIM = $_POST['NOMANIM'];
$DATEVALIDITEANIM = $_POST['DATEVALIDITEANIM'];
$DUREEANIM = $_POST['DUREEANIM'];
$LIMITEAGE = $_POST['LIMITEAGE'];
$TARIFANIM = $_POST['TARIFANIM'];
$NBREPLACEANIM = $_POST['NBREPLACEANIM'];
$DESCRIPTANIM = $_POST['DESCRIPTANIM'];
$COMMENTANIM = $_POST['COMMENTANIM'];
$DIFFICULTANIM = $_POST['DIFFICULTEANIM'];
$req = "INSERT INTO animation (CODEANIM, CODETYPEANIM, NOMANIM, DATECREATIONANIM, DATEVALIDITEANIM, DUREEANIM, LIMITEAGE, TARIFANIM, NBREPLACEANIM, DESCRIPTANIM, COMMENTANIM, DIFFICULTEANIM)
VALUES ('$CDANIM', '$CDTYPEANIM' , '$NOMANIM' , NOW(), '$DATEVALIDITEANIM', '$DUREEANIM', '$LIMITEAGE', '$TARIFANIM', '$NBREPLACEANIM', '$DESCRIPTANIM', '$COMMENTANIM', '$DIFFICULTANIM');" ;
$res = mysqli_query(bddConnect(), $req);
header('Location: index.php?index=animation');
?>
